spring.application.name=7_SpringBoot_CRUD_Operation

spring.datasource.url= jdbc:postgresql://localhost:5432/Company_Crud_operation_Postman
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect