spring.application.name=9_SB_Java_Mail_Send

#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raskarpratik44@gmail.com
#google app password
spring.mail.password=hvqq zyte tbag javi                
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requires=true